export type CsvCity = {
  address?: string,
  postal_code?: string,
  country?: string,
  federal_district?: string,
  region_type?: string,
  region?: string,
  area_type?: string,
  city_type?: string,
  city?: string,
  settlement_type?: string,
  settlement?: string,
  kladr_id?: string,
  fias_id?: string,
  fias_level?: string,
  capital_marker: string,
  okato?: string,
  oktmo?: string,
  tax_office?: string,
  timezone?: string,
  geo_lat?: string,
  geo_lon?: string,
  population?: string,
  foundation_year?: string,
}
